MAIN_TEST_DATA = {'current_date': 1724266250,
 'homeworks': [{'date_updated': '2024-08-07T04:59:08Z',
                'homework_name': 'theartemio__django_testing.zip',
                'id': 1297189,
                'lesson_name': 'Финальный проект спринта: Vice Versa',
                'reviewer_comment': 'Принято',
                'status': 'approved'},
               {'date_updated': '2024-07-31T08:37:05Z',
                'homework_name': 'theartemio__django_sprint4.zip',
                'id': 1288777,
                'lesson_name': 'Финальный проект спринта: доработка Блогикум',
                'reviewer_comment': 'Принято 👍🏻',
                'status': 'approved'},
               {'date_updated': '2024-07-03T13:30:03Z',
                'homework_name': 'theartemio__django_sprint3.zip',
                'id': 1266267,
                'lesson_name': 'Финальный проект спринта: публикации для '
                               'Блогикум',
                'reviewer_comment': 'Принято 👍🏻',
                'status': 'approved'},
               {'date_updated': '2024-06-10T12:04:01Z',
                'homework_name': 'theartemio__django_sprint1.zip',
                'id': 1247420,
                'lesson_name': 'Финальный проект спринта: Блогикум',
                'reviewer_comment': 'Принято 👍🏻',
                'status': 'approved'},
               {'date_updated': '2024-05-13T21:59:56Z',
                'homework_name': 'command_string_decipher_3.zip',
                'id': 1218318,
                'lesson_name': 'Финальное задание спринта: Шифрованные '
                               'инструкции',
                'reviewer_comment': 'Отличная работа, молодец! Принято)',
                'status': 'approved'},
               {'date_updated': '2024-05-02T19:02:15Z',
                'homework_name': 'robot_delivery_3.zip',
                'id': 1210318,
                'lesson_name': 'Финальное задание спринта: служба доставки',
                'reviewer_comment': 'Принято 👍🏻',
                'status': 'approved'},
               {'date_updated': '2024-04-23T13:40:50Z',
                'homework_name': 'theartemio__the_snake.zip',
                'id': 1199589,
                'lesson_name': 'Финальный проект спринта: «Изгиб Питона»',
                'reviewer_comment': 'Принято 👍🏻',
                'status': 'approved'}]}


# Testing parse homework
SHITTY_STATUSES_TEST_DATA = {'current_date': 1724266250,
 'homeworks': [{'date_updated': '2024-08-07T04:59:08Z',
                'homework_name': 'theartemio__django_testing.zip',
                'id': 1297189,
                'lesson_name': 'Финальный проект спринта: Vice Versa',
                'reviewer_comment': 'Принято',
                'status': 'ass'},
               {'date_updated': '2024-07-31T08:37:05Z',
                'homework_name': 'theartemio__django_sprint4.zip',
                'id': 1288777,
                'lesson_name': 'Финальный проект спринта: доработка Блогикум',
                'reviewer_comment': 'Принято 👍🏻',
                'status': 'shit'},
               {'date_updated': '2024-07-03T13:30:03Z',
                'homework_name': 'theartemio__django_sprint3.zip',
                'id': 1266267,
                'lesson_name': 'Финальный проект спринта: публикации для '
                               'Блогикум',
                'reviewer_comment': 'Принято 👍🏻',
                'status': 'fuck'},
               {'date_updated': '2024-06-10T12:04:01Z',
                'homework_name': 'theartemio__django_sprint1.zip',
                'id': 1247420,
                'lesson_name': 'Финальный проект спринта: Блогикум',
                'reviewer_comment': 'Принято 👍🏻',
                'status': 'fuck'},
               {'date_updated': '2024-05-13T21:59:56Z',
                'homework_name': 'command_string_decipher_3.zip',
                'id': 1218318,
                'lesson_name': 'Финальное задание спринта: Шифрованные '
                               'инструкции',
                'reviewer_comment': 'Отличная работа, молодец! Принято)',
                'status': 'approved'},
               {'date_updated': '2024-05-02T19:02:15Z',
                'homework_name': 'robot_delivery_3.zip',
                'id': 1210318,
                'lesson_name': 'Финальное задание спринта: служба доставки',
                'reviewer_comment': 'Принято 👍🏻',
                'status': 'fuck'},
               {'date_updated': '2024-04-23T13:40:50Z',
                'homework_name': 'theartemio__the_snake.zip',
                'id': 1199589,
                'lesson_name': 'Финальный проект спринта: «Изгиб Питона»',
                'reviewer_comment': 'Принято 👍🏻',
                'status': 'shit'}]}

# Testing check_response

TEST_CASE_NO_HW_KEY = {'current_date': 1724266250, 'homewoKs': []}
TEST_CASE_NO_CD_KEY = {'currentdate': 1724266250, 'homeworks': []}

TEST_CASE_BAD_VALUE_TYPE_INT = {'current_date': '1724266250', 'homeworks': []}
TEST_CASE_BAD_VALUE_TYPE_DICT = {'current_date': 1724266250, 'homeworks': ()}